### ISSUE TITLE
Breaking changes in v2.0.0

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand-sdk#343]
Itemizes functionality that will be removed in the upcoming major release.

Task list for algorand-sdk-testing stories:
- [x] https://github.com/algorand/algorand-sdk-testing/issues/201 - https://github.com/algorand/go-algorand-sdk/pull/444
- [x] https://github.com/algorand/algorand-sdk-testing/issues/202 - N/A 
- [x] https://github.com/algorand/algorand-sdk-testing/issues/223 - https://github.com/algorand/go-algorand-sdk/pull/445
- [x] https://github.com/algorand/algorand-sdk-testing/issues/254 - https://github.com/algorand/go-algorand-sdk/pull/445
- [x] https://github.com/algorand/algorand-sdk-testing/issues/255 - https://github.com/algorand/go-algorand-sdk/pull/451
- [x] https://github.com/algorand/generator/issues/46 - https://github.com/algorand/generator/pull/47
- [x] https://github.com/algorand/go-algorand-sdk/pull/450
